version: '3'

services:
  mysql:
    image: 'mysql'
    container_name: 'java-mysql'
    environment:
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=Aks-662828'
      - 'MYSQL_ROOT_PASSWORD=Aks-662828'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"








