version: '3.1'

services:
  db:
    image: mysql
    container_name: java-mysql
    ports:
      - "33068:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=database











