CREATE TABLE IF NOT EXISTS user (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
login VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS role (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
role_name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS event (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
event_name VARCHAR(255) NOT NULL,
user_id INT NOT NULL,
file_id INT NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS file (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
file_name VARCHAR(255),
location VARCHAR(255),
type VARCHAR(255),
size FLOAT DEFAULT 0.00,
last_modified TIMESTAMP DEFAULT NULL ON UPDATE NOW(),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS user_role (
user_id INT,
role_id INT,
PRIMARY KEY(user_id)
);