ALTER TABLE event
ADD FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (file_id) REFERENCES file(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE user_role
ADD FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE ON UPDATE CASCADE;